spring.application.name=palermus-api

#Database connection
spring.datasource.url=${URL_DB}palermus
spring.datasource.username=${NAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.format-sql=true

server.port=${SERVER_PORT:8081}
api.security.token.secret=${JWT_SECRET}

# Secret key para encriptacion determinista de datos sensibles (Debe tener 32 caracteres para AES-256)
app.encryption.secret=${ENCRYPTION}

