spring.application.name=palermus-api

#Database connection
spring.datasource.url=${URL_DB}palermus
spring.datasource.username=${NAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081
api.security.token.secret=${JWT_SECRET}
